version: '3.8'

services:
  mysql:
    image: mysql:5.7
    container_name: nodejs-mysql
    environment:
      MYSQL_ROOT_PASSWORD: Password
      MYSQL_ROOT_USER: root
      MYSQL_DATABASE: task_manager_db
    ports:
      - "3306:3306"
    volumes:
      - ~/mysql:/var/lib/mysql

  nodejs-app:
    build: .
    container_name: nodejs-app
    ports:
      - "3000:3000"
    links:
      - mysql
    volumes:
      - .:/usr/src/app

volumes:
  mysql-data:
